# spring
spring:

  # profiles
  profiles:
    active: dev
  # swagger
  swagger:
    enabled: true
    base-package: com.mozhumz.usermanage.web.controller
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: error
    usermanage-heshituina.usermanage: info
# mybatis plus
mybatis-plus:
  type-aliases-package: com.mozhumz.usermanage.model.entity
  mapper-locations: classpath:mappers/*.xml

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000