# spring
spring:
  # datasource
  datasource:
    # druid
    druid:
      url: jdbc:mysql://localhost:3306/usermanage_heshituina_pidu?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
# log
logging:
  level:
    com.mozhumz.usermanage: info