# spring
spring:
  application:
    name: usermanage
  session:
    store-type: redis
  redis:
    port: 6379
    database: 1
    password: 123456
  # datasource
  datasource:
    # druid
    druid:
      url: jdbc:mysql://localhost:3306/heshituina_usermanage_pidu?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/

urlPre:
  web: http://127.0.0.1:8080/usermanage/index.html
  sso: http://127.0.0.1:8080/zuul/api/login/checkLogin
  webOut: http://127.0.0.1:8080/balance/api/login/logOut